export const linkedinContent = {
  'customer-order-intake': {
    audience: 'Geschäftsführer, Leitung Vertriebsinnendienst, Operations, ERP-Verantwortliche',
    angles: [
      'Problem-Post: Der Auftrag kommt als PDF, geprüft wird trotzdem Zeile für Zeile.',
      'Failure-Post: Eine Preisabweichung ist kein Fehler des Workflows, sondern sein wichtigstes Ergebnis.',
      'Technik-Post: Idempotenz und Quellenbezug verhindern Doppelanlage und unprüfbare Extraktion.',
      'Kapazitäts-Post: Erst die Vorbereitung standardisieren, nicht die ERP-Freigabe automatisieren.',
    ],
    hooks: [
      'Ein Kundenauftrag kommt als PDF per E-Mail rein.',
      'Dieser Workflow hat den Auftrag nicht ans ERP weitergegeben. Genau das war richtig.',
      'Die interessanteste Zahl in dieser Demo ist nicht die Confidence. Es sind 0 externe Writes.',
      'Auftragserfassung ist selten spektakulär. Genau deshalb lohnt es sich, hinzusehen.',
    ],
    ctas: [
      'Wo entstehen bei Ihnen die meisten Rückfragen: Artikel, Preis oder Liefertermin?',
      'Welche Abweichung müsste in Ihrem Prozess immer einen Menschen stoppen lassen?',
      'Wie viele Bestellformate landen heute im Vertriebsinnendienst?',
    ],
    visual: 'Geteilte Ansicht: links synthetische Bestellung, rechts ERP-Entwurf. Preisabweichung in Orange; Freigabefeld sichtbar; Footer „0 externe Writes“.',
    posts: [
      `Ein Kundenauftrag kommt als PDF per E-Mail rein.\n\nJemand prüft Kundennummer, Artikel, Preis, Menge, Liefertermin und Adresse. Danach werden die Daten ins ERP übertragen.\n\nDas Problem ist nicht nur das Copy/Paste. Kritisch wird es dort, wo eine Zeile plausibel aussieht, aber nicht zum Stammdatensatz passt.\n\nFür eine Synthetic Demo habe ich den Ablauf deshalb nicht als automatische ERP-Buchung gebaut, sondern als prüfbare Vorbereitung:\n\n– Bestelldaten strukturieren\n– Artikel und Preise gegen synthetische Stammdaten prüfen\n– fehlende Angaben markieren\n– jede Abweichung mit Quelle anzeigen\n– einen ERP-Payload vorbereiten\n– Freigabe beim Menschen lassen\n\nIm Happy Path spart das Such- und Übertragungsarbeit. Im wichtigen Fall stoppt das System.\n\nKein „autonomer Agent“. Kein erfundener Liefertermin. Keine stille Buchung.\n\nWo entstehen bei Ihnen die meisten Rückfragen: Artikel, Preis oder Liefertermin?`,
      `Dieser Workflow hat den Auftrag nicht weiterverarbeitet.\n\nUnd genau das war das richtige Ergebnis.\n\nIm synthetischen Test bestellt ein Kunde zehn Schutzgitter zu 221 Euro. Im Artikelstamm stehen 240,50 Euro. Die Abweichung beträgt 8,1 Prozent.\n\nEin System, das nur Text extrahiert, könnte daraus einen sauber formatierten Fehler machen. Ein brauchbarer Prozess muss an dieser Stelle sichtbar anhalten.\n\nDie Demo zeigt deshalb:\n\n1. die erkannte Position,\n2. Bestellpreis und Stammpreis,\n3. die Quelle der Daten,\n4. den Status „Prüfung erforderlich“,\n5. eine menschliche Prüfnotiz,\n6. einen vorbereiteten, aber noch nicht geschriebenen ERP-Entwurf.\n\nDas Ziel ist nicht, den Vertriebsinnendienst aus der Entscheidung zu entfernen. Das Ziel ist, dass er seine Zeit auf die Abweichung verwendet—nicht auf das Abschreiben der unauffälligen Zeilen.\n\nWelche Preisabweichung dürfte bei Ihnen niemals automatisch durchlaufen?`,
      `Was passiert, wenn dieselbe Bestellung zweimal eingeht?\n\nIn vielen Demos endet die Geschichte nach der erfolgreichen Extraktion. In realen Abläufen kommt danach eine unangenehmere Frage: Wird der Auftrag doppelt angelegt?\n\nDer Prototyp verwendet deshalb einen Idempotenzschlüssel aus dem Eingangsereignis. Beim Replay wird kein zweiter Entwurf erzeugt. Der Lauf endet sichtbar als „Duplikat erkannt“.\n\nZusätzlich speichert der Auditverlauf:\n\n– Run-ID\n– Eingangsquelle\n– Regelprüfungen\n– Ausnahmezustand\n– menschliche Entscheidung\n– terminales Ergebnis\n\nAuch hier bleibt der ERP-Adapter gemockt. Die technische Aussage ist nicht „bereit für Produktion“, sondern enger: Der Ablauf ist gebaut und reproduzierbar testbar, einschließlich Replay und Fehlerpfad.\n\nWelche Ereignis-ID könnten Sie heute zuverlässig für eine doppelte Bestellung verwenden?`,
    ],
    carousel: [
      'Titel: Ein Auftrag kommt als PDF. Was sollte wirklich automatisiert werden?',
      'Manuell heute: lesen, suchen, vergleichen, übertragen.',
      'Eingang: Kunde, Artikel, Menge, Preis, Termin und Adresse.',
      'Regelprüfung: Bestellpreis 221 € vs. Stammpreis 240,50 €.',
      'Stop Condition: 8,1 % Abweichung → Prüfung erforderlich.',
      'Mensch: Abweichung klären, Notiz hinterlegen, freigeben oder ablehnen.',
      'Ergebnis: ERP-Entwurf vorbereitet, 0 externe Writes.',
      'Frage: Welche Abweichung muss Ihren Prozess immer stoppen?',
    ],
    video: [
      ['0–08 s', 'Bestell-PDF und manuelle Prüfliste zeigen.', 'Ein Kundenauftrag kommt als PDF. Heute werden Artikel, Preis und Termin oft Zeile für Zeile geprüft.'],
      ['08–18 s', 'Testfall „Preisabweichung“ auswählen.', 'Die Demo strukturiert den Eingang und vergleicht ihn mit synthetischen Stammdaten.'],
      ['18–32 s', 'Workflow ausführen; Regelprüfung und 8,1-%-Abweichung zeigen.', 'Hier passt der Preis nicht. Der Workflow darf deshalb nicht einfach weitermachen.'],
      ['32–45 s', 'Status „Prüfung erforderlich“, Quelle und Prüfnotiz zeigen.', 'Die Abweichung bleibt mit Quelle sichtbar. Ein Mensch entscheidet.'],
      ['45–57 s', 'Freigabe klicken und Payload öffnen.', 'Freigabe bedeutet nur: Der Entwurf ist geprüft. Es wurde nichts ins ERP geschrieben.'],
      ['57–65 s', 'Run-ID und „0 Writes“ einblenden.', 'Das Ziel: weniger Copy/Paste und mehr Aufmerksamkeit für die Ausnahme.'],
    ],
  },
  'machine-service-triage': {
    audience: 'Serviceleiter, After-Sales Operations, technischer Support, Geschäftsführer Maschinenbau',
    angles: [
      'Problem-Post: Der erste Servicekontakt enthält selten alle Informationen.',
      'Failure-Post: Ein Schutztürhinweis darf keine automatische Ferndiagnose auslösen.',
      'Operations-Post: Priorität und Zuständigkeit vorbereiten, bevor ein Techniker übernimmt.',
      'Knowledge-Post: Installierte Basis und Servicehistorie als Kontext, nicht als Ursachenbeweis.',
    ],
    hooks: [
      '„Anlage steht. Bitte dringend zurückrufen.“ Damit beginnt erstaunlich viel Servicearbeit.',
      'Diese Demo nennt bewusst keine Fehlerursache.',
      'Ein guter Service-Workflow beantwortet zuerst: Welche Maschine? Welche Auswirkung? Welche Information fehlt?',
      'Schneller reagieren heißt nicht schneller raten.',
    ],
    ctas: [
      'Welche drei Angaben fehlen in Ihren Serviceanfragen am häufigsten?',
      'Welche Meldung muss bei Ihnen sofort an einen Menschen eskalieren?',
      'Wie wird heute die installierte Maschine zu einer E-Mail gefunden?',
    ],
    visual: 'Service-Inbox links; Maschinenkarte, Priorität, fehlende Angaben und Audit-Timeline rechts. Rote Stop-Zone bei Sicherheitsbezug.',
    posts: [
      `„Anlage steht. Bitte dringend zurückrufen.“\n\nDamit beginnt erstaunlich viel Servicearbeit.\n\nBevor ein Techniker helfen kann, fehlen oft Maschinennummer, Fehlercode, Foto, Zeitpunkt oder eine klare Beschreibung der Auswirkung. Dann folgen Rückfragen, Suche im installierten Bestand und manuelle Priorisierung.\n\nIch habe dafür eine Synthetic Demo gebaut, die genau diese Vorarbeit übernimmt:\n\n– Maschine und Baureihe zuordnen\n– Stillstand und Sicherheitsbezug trennen\n– vorhandene Anhänge und Fehlercodes auflisten\n– fehlende Informationen als konkrete Rückfragen formulieren\n– Priorität und Service-Queue vorschlagen\n– Ticketentwurf mit Quellen vorbereiten\n\nWichtig: Die Demo behauptet keine technische Ursache. Sie hilft, den Fall schneller und vollständiger an die richtige Person zu geben.\n\nSchneller reagieren heißt nicht schneller raten.\n\nWelche drei Angaben fehlen in Ihren Serviceanfragen am häufigsten?`,
      `Diese Demo nennt bewusst keine Fehlerursache.\n\nDer Testfall enthält eine Schutztürmeldung nach einem mechanischen Umbau. Die Produktion steht. Anhänge fehlen.\n\nEine vermeintlich „smarte“ Automatisierung könnte aus Fehlercode und Historie eine Diagnose formulieren. Das wäre hier die falsche Aufgabe.\n\nDer Workflow macht stattdessen Folgendes:\n\n1. Sicherheitsbezug erkennen,\n2. Priorität auf manuelle Eskalation setzen,\n3. Ferndiagnose ausdrücklich sperren,\n4. Maschinendaten und vorhandene Evidenz zeigen,\n5. fehlende Informationen nachfordern,\n6. einen Ticketentwurf vorbereiten.\n\nDas Ergebnis ist „Zur manuellen Prüfung“. Kein Lösungsvorschlag, der wie eine technische Freigabe klingt.\n\nGerade im Maschinenservice ist ein guter Stop-Mechanismus oft glaubwürdiger als ein beeindruckender Happy Path.\n\nWelche Meldung müsste in Ihrem Serviceprozess immer sofort eskalieren?`,
      `Wie viel Servicezeit geht verloren, bevor der eigentliche Fachfall überhaupt beginnt?\n\nNicht bei der Reparatur—bei der Zuordnung.\n\nWelche Maschine ist betroffen? Welche Baureihe? Gibt es Gewährleistung? Wann war der letzte Service? Ist die Produktion gestoppt? Liegt ein Foto vor?\n\nDer Prototyp verbindet diese Fragen in einem prüfbaren Intake. Jede Information zeigt ihre Quelle. Unklare Maschinen landen nicht automatisch bei irgendeinem Techniker, sondern als gezielte Rückfrage.\n\nDer technische Kern ist unspektakulär und wichtig: strukturierter Eingang, feste Regeln, Auditverlauf, Idempotenz und ein gemockter Ticket-Adapter.\n\nDas kommerzielle Versprechen wäre deshalb nicht „KI repariert Maschinen“. Es wäre: weniger Rückfragen, schneller bei der richtigen Person und ein vollständigerer Servicefall.\n\nWie wird bei Ihnen heute eine freie E-Mail der installierten Maschine zugeordnet?`,
    ],
    carousel: [
      'Titel: „Anlage steht.“ Was fehlt, bevor Service sinnvoll helfen kann?',
      'Eingang: E-Mail, Maschinenbezug, Fehlercode, Fotos und Auswirkung.',
      'Kontext: installierte Basis, Baureihe, Standort, letzte Wartung.',
      'Triage: Stillstand, Priorität, zuständige Queue, fehlende Angaben.',
      'Grenze: Keine Root Cause ohne technische Evidenz.',
      'Stop Condition: Schutztürmeldung nach Umbau → manuelle Eskalation.',
      'Ergebnis: Ticketentwurf mit Quellen, 0 externe Writes.',
      'Frage: Was fehlt in Ihren Serviceanfragen am häufigsten?',
    ],
    video: [
      ['0–08 s', 'Service-E-Mail „Anlage steht“ zeigen.', 'Eine dringende Serviceanfrage ist oft noch kein bearbeitbarer Servicefall.'],
      ['08–19 s', 'Maschinenkarte und Eingangsdaten zeigen.', 'Der Workflow ordnet Maschine, Baureihe, Fehlercode und Auswirkung zu.'],
      ['19–32 s', 'Testfall „Sicherheitsrelevanter Hinweis“ starten.', 'Bei einer Schutztürmeldung nach Umbau muss das System aufhören, technisch zu raten.'],
      ['32–45 s', 'Rote Ausnahme und „keine Ferndiagnose“ zeigen.', 'Der Fall wird manuell eskaliert. Fehlende Evidenz bleibt sichtbar.'],
      ['45–58 s', 'Ticket-Payload und Audit öffnen.', 'Vorbereitet werden Priorität, zuständige Queue, Rückfragen und Quellen—nicht die Ursache.'],
      ['58–67 s', '0 Writes und Status einblenden.', 'Das Ziel: schneller beim Fachmenschen, ohne falsche Sicherheit.'],
    ],
  },
  'spare-parts-inquiry': {
    audience: 'Leitung Ersatzteilservice, Serviceleiter, Installed Base Management',
    angles: ['Ambiguität statt Bilderkennung feiern.', 'BOM- und Nachfolgerdaten als eigentlicher Engpass.', 'Synthetische Verfügbarkeit klar von echtem Bestand trennen.'],
    hooks: ['Ein Foto zeigt ein Ventil. Aber welches?', 'Zwei plausible Ersatzteile sind kein Treffer.', 'Bei Ersatzteilen ist „ähnlich“ kein Freigabekriterium.'],
    ctas: ['Wie oft fehlt bei Anfragen die Maschinennummer?', 'Wo werden Nachfolger heute gepflegt?', 'Welche Information löst eine Varianten-Ambiguität zuverlässig auf?'],
    visual: 'Zwei gleich plausible Teile nebeneinander, Confidence-Werte, BOM-Revision und großer Status „Keine automatische Auswahl“.',
    posts: [
      `Ein Foto zeigt ein Ventil. Aber welches?\n\nIm synthetischen Test passen Bauform und Einbauort zu zwei Varianten: 24 V und 230 V. Beide sehen plausibel aus. Das Typenschild ist nicht lesbar.\n\nEin schlechter Workflow wählt den Kandidaten mit 71 Prozent Confidence. Ein brauchbarer Workflow erkennt: Zwei plausible Teile sind kein Treffer.\n\nDie Demo zeigt deshalb beide Kandidaten mit:\n\n– Artikelnummer\n– BOM-Revision und Position\n– Confidence als Hinweis\n– synthetischem Bestand\n– fehlender Information zur eindeutigen Auswahl\n\nDer Prozess stoppt und fordert Spannung oder Typenschild an.\n\nGerade bei Ersatzteilen ist ein menschlich kontrollierter Ausnahmeweg wichtiger als eine beeindruckende Bilderkennung. Die Auswahl darf erst erfolgen, wenn Maschine, Variante und freigegebene BOM zusammenpassen.\n\nWelche Information löst bei Ihnen eine Varianten-Ambiguität zuverlässig auf?`,
      `Das schwierigste Problem im Ersatzteilprozess ist möglicherweise nicht die Anfrage.\n\nEs sind die Daten dahinter.\n\nEin Kunde nennt die Maschinennummer. Die BOM zeigt ein altes HMI. Eine Nachfolgerliste enthält ein neues Gerät. Aber der Nachfolger ist für diese Variante noch nicht technisch freigegeben.\n\nDie Demo markiert genau diese Grenze:\n\n– Altteil erkannt\n– Bestand synthetisch bei null\n– möglicher Nachfolger gefunden\n– Freigabestatus fehlt\n– automatische Auswahl gesperrt\n\nDamit wird sichtbar, was ein Pilot wirklich braucht: saubere Maschinenstruktur, revisionssichere BOM, Nachfolgerbeziehung und Freigabestatus.\n\nDie Automatisierung kann suchen und vorbereiten. Engineering oder Ersatzteilservice müssen die technische Eignung verantworten.\n\nWo werden Nachfolger bei Ihnen heute gepflegt—ERP, Excel oder im Kopf einzelner Personen?`,
    ],
  },
  'lastenheft-delta-check': {
    audience: 'Leitung Engineering, technischer Vertrieb, Projektleitung',
    angles: ['Quellenbasierte Delta-Matrix statt Summary.', 'Widerspruch zwischen zwei Seiten als Stop Condition.', 'Messbare Abnahmekriterien früh nachfordern.'],
    hooks: ['Seite 3 sagt 12 Sekunden. Seite 28 sagt 15.', 'Ein Lastenheft zusammenzufassen ist leicht. Es prüfbar zu vergleichen ist die eigentliche Aufgabe.', '„Hohe Prüfgenauigkeit“ ist keine abnehmbare Anforderung.'],
    ctas: ['Welche Anforderung erzeugt bei Ihnen die meisten Nachträge?', 'Wie werden Widersprüche heute dokumentiert?', 'Muss jede Matrixzeile auf eine Seite zurückverweisen?'],
    visual: 'Anforderungsmatrix mit Seite, Kundenwert, internem Standard, Delta und Frage; widersprüchliche Taktzeit doppelt markiert.',
    posts: [
      `Seite 3 sagt 12 Sekunden. Seite 28 sagt 15.\n\nEin Lastenheft einfach zusammenzufassen, hilft an dieser Stelle nicht. Der Widerspruch würde vielleicht in einem sauberen Absatz verschwinden.\n\nDie Synthetic Demo arbeitet deshalb zeilenweise:\n\n– Anforderung extrahieren\n– Quelle und Seite speichern\n– internen Standard gegenüberstellen\n– Match, Delta oder fehlendes Kriterium markieren\n– Widersprüche zwischen Quellen erkennen\n– offene Frage für die Projektklärung vorbereiten\n\nBeim widersprüchlichen Takt stoppt der Prozess. Er entscheidet nicht, welcher Wert „wahrscheinlich“ gemeint ist.\n\nDer Nutzen liegt nicht in einer magischen Machbarkeitsaussage. Er liegt in einer früheren, prüfbaren Fragenliste und weniger übersehenen Abweichungen.\n\nWie werden Widersprüche zwischen E-Mail, Lastenheft und Anlagen heute bei Ihnen dokumentiert?`,
      `„Hohe Prüfgenauigkeit“ klingt technisch. Abnehmbar ist es nicht.\n\nFür Engineering und Projektleitung ist eine vage Anforderung oft teurer als eine sichtbar fehlende. Ohne Messgröße, Toleranz, Prüfverfahren oder Randbedingung bleibt unklar, wann die Maschine die Anforderung erfüllt.\n\nDer Delta-Workflow markiert solche Sätze deshalb nicht als „verstanden“. Er erzeugt eine offene Frage mit Seitenbezug und stellt den internen Standard daneben.\n\nDie menschliche Aufgabe bleibt:\n\n– technische Interpretation\n– Machbarkeitsprüfung\n– Risikobewertung\n– Klärung mit dem Kunden\n\nDie Automatisierung strukturiert den Vergleich. Sie genehmigt keine technische Lösung.\n\nWelche Formulierung in Lastenheften erzeugt bei Ihnen regelmäßig späte Rückfragen oder Nachträge?`,
    ],
  },
  'invoice-po-matching': {
    audience: 'Leitung Kreditorenbuchhaltung, Einkauf, Finance Operations, ERP-Verantwortliche',
    angles: ['3-Wege-Match als Kapazitätsproblem.', 'Geänderte IBAN als kompromisslose Stop Condition.', 'E-Rechnung macht strukturierte Eingänge verfügbar, aber nicht automatisch richtig.'],
    hooks: ['Alle Beträge passen. Trotzdem darf diese Rechnung nicht weiter.', 'Eine E-Rechnung ist strukturiert. Das bedeutet nicht, dass sie freigegeben ist.', '20 Stück auf der Rechnung. 18 im Wareneingang.'],
    ctas: ['Welche Abweichung kostet heute die meiste Klärungszeit?', 'Wie wird eine neue IBAN bei Ihnen unabhängig verifiziert?', 'Ist Wareneingang oder Preisabweichung der häufigere Ausnahmeweg?'],
    visual: 'Drei Spalten Rechnung–PO–Wareneingang; IBAN-Zeile rot über die ganze Breite; Freigabe gesperrt.',
    posts: [
      `Alle Beträge passen. Trotzdem darf diese Rechnung nicht weiter.\n\nIm synthetischen Test stimmen Lieferant, Bestellung, Positionen, Menge, Preis und Steuer. Nur die IBAN auf der Rechnung weicht vom freigegebenen Lieferantenstamm ab.\n\nGenau deshalb endet der Lauf als „Zur manuellen Prüfung“.\n\nDer Workflow führt einen nachvollziehbaren 3-Wege-Abgleich durch:\n\n– Rechnung gegen Bestellung\n– Menge gegen Wareneingang\n– Preis gegen PO\n– Steuer und Gesamtbetrag\n– IBAN gegen Lieferantenstamm\n\nBei geänderten Bankdaten gibt es keine Toleranzregel und keine automatische Stammdatenänderung. Die Verifizierung muss über einen freigegebenen, unabhängigen Prozess erfolgen.\n\nDie Demo schreibt weder ins ERP noch ins Finanzsystem. Sie bereitet eine Entscheidung vor und zeigt, warum die Buchung blockiert ist.\n\nWie wird eine neue IBAN bei Ihnen heute unabhängig verifiziert?`,
      `20 Stück auf der Rechnung. 18 im Wareneingang.\n\nDer Rechnungsbetrag kann rechnerisch korrekt sein und trotzdem nicht zur realen Lieferung passen.\n\nFür eine Synthetic Demo habe ich Rechnung, Bestellung und Wareneingang als getrennte Quellen modelliert. Der Workflow vergleicht jede Position und zeigt die Abweichung dort, wo sie entsteht.\n\nDas Ergebnis ist kein automatisches „bezahlen“ oder „nicht bezahlen“. Es ist ein prüfbarer Fall für Einkauf oder Kreditorenbuchhaltung:\n\n– Welche Position weicht ab?\n– Welche Quelle sagt was?\n– Ist es eine Teillieferung, ein Buchungsrückstand oder ein Rechnungsfehler?\n– Wer muss klären?\n\nGerade mit zunehmender E-Rechnung wird der strukturierte Eingang leichter. Die fachliche Ausnahme verschwindet dadurch nicht.\n\nWelche Abweichung verursacht bei Ihnen mehr Arbeit: Menge, Preis oder fehlender Wareneingang?`,
      `Eine E-Rechnung ist maschinenlesbar. Sie ist damit noch nicht automatisch richtig.\n\nDeutschland hat den B2B-E-Rechnungsprozess schrittweise verpflichtend gemacht. Das schafft strukturierte Daten—und eine gute Gelegenheit, die Prüfung neu zu denken.\n\nDie Demo trennt drei Ebenen:\n\n1. Format und Pflichtfelder,\n2. fachlicher Abgleich gegen PO und Wareneingang,\n3. sensible Ausnahme mit menschlicher Freigabe.\n\nEin Adapterfehler führt in einen begrenzten Retry. Ein Replay erzeugt keinen zweiten Fall. Eine geänderte IBAN stoppt. Jeder Lauf erhält eine Run-ID und ein Audit.\n\nDas ist noch keine produktive Finanzintegration. Es ist ein gebauter, reproduzierbarer Prozesskern mit gemocktem ERP-Adapter.\n\nWelche Prüfregel wäre für einen ersten Pilot ausreichend eng und trotzdem wirtschaftlich relevant?`,
    ],
    carousel: [
      'Titel: Alle Beträge passen. Warum stoppt die Rechnung trotzdem?',
      'Quellen: E-Rechnung, Bestellung, Wareneingang, Lieferantenstamm.',
      '3-Wege-Match: Preis, Menge und PO stimmen.',
      'Sensible Prüfung: Rechnungs-IBAN ≠ freigegebene IBAN.',
      'Stop Condition: keine automatische Buchung, keine Stammdatenänderung.',
      'Mensch: Bankdaten unabhängig verifizieren und Entscheidung dokumentieren.',
      'Ergebnis: Buchungsentwurf blockiert, Audit vollständig, 0 Writes.',
      'Frage: Wie wird eine neue IBAN bei Ihnen verifiziert?',
    ],
    video: [
      ['0–07 s', 'Rechnung, PO und Wareneingang nebeneinander zeigen.', 'Drei Quellen stimmen scheinbar überein. Trotzdem darf diese Rechnung nicht weiter.'],
      ['07–19 s', 'Testfall „Geänderte IBAN“ öffnen.', 'Der Workflow prüft Lieferant, Bestellung, Positionen, Menge, Preis und Steuer.'],
      ['19–31 s', 'Grüne Checks nacheinander zeigen.', 'Alle fachlichen Positionen passen.'],
      ['31–43 s', 'Rote IBAN-Abweichung und Stop-Status zeigen.', 'Aber die Bankverbindung weicht vom freigegebenen Lieferantenstamm ab.'],
      ['43–56 s', 'Menschliche Frage und gesperrten Payload zeigen.', 'Keine automatische Buchung. Keine automatische Stammdatenänderung. Erst unabhängig verifizieren.'],
      ['56–65 s', 'Audit und 0 Writes einblenden.', 'Die wichtigste Funktion ist hier nicht Geschwindigkeit, sondern der richtige Stop.'],
    ],
  },
  'rfq-prequalification': {
    audience: 'Leitung technischer Vertrieb, Angebotswesen, Engineering',
    angles: ['RFQ als Vollständigkeitsprüfung, nicht als Preisautomat.', 'Widersprüchliche Taktzeit sichtbar machen.', 'Rückfragen mit Evidenz statt generischem Summary.'],
    hooks: ['Eine Anfrage ist noch kein belastbares Angebot.', '12 Sekunden in der E-Mail, 15 im Lastenheft.', 'Das System darf Anforderungen finden. Machbarkeit muss Engineering verantworten.'],
    ctas: ['Welche drei Angaben fehlen in RFQs am häufigsten?', 'Wann wird Engineering heute eingebunden?', 'Welcher Widerspruch wird meist erst im Projekt entdeckt?'],
    visual: 'RFQ-Completeness Sheet: bekannte Anforderungen, fehlende Felder, Widerspruch mit zwei Quellen, Preisfeld bewusst leer.',
    posts: [
      `Eine Anfrage ist noch kein belastbares Angebot.\n\nOft fehlen Jahresmenge, Ziel-SOP, Schnittstellen oder ein messbares Abnahmekriterium. Trotzdem beginnt intern bereits die Suche nach einer Lösung.\n\nDer RFQ-Prototyp macht deshalb nur eine eng definierte Aufgabe:\n\n– Anforderungen und Quellen strukturieren\n– fehlende Kernfelder markieren\n– Widersprüche zwischen E-Mail und Dokumenten zeigen\n– konkrete Rückfragen vorbereiten\n– einen Review-Entwurf anlegen\n\nPreis und technische Machbarkeit bleiben leer. Nicht weil das System „noch nicht intelligent genug“ wäre, sondern weil diese Entscheidung Fachwissen, Daten und Verantwortung braucht.\n\nRFQ ist in diesem Lab bewusst ein Experiment unter zehn—nicht das vorab gewählte Produkt.\n\nWelche drei Angaben fehlen in technischen Anfragen bei Ihnen am häufigsten?`,
      `12 Sekunden in der E-Mail. 15 Sekunden im Lastenheft.\n\nEin automatisches Summary könnte beide Werte erwähnen. Ein brauchbarer Vorqualifizierungsprozess muss den Widerspruch als Blocker behandeln.\n\nDie Demo speichert deshalb jede Aussage mit Quelle und erzeugt den Status „Zur manuellen Prüfung“. Erst nach der Klärung darf aus dem Eingang ein belastbarer Review-Fall werden.\n\nWas sie nicht macht:\n\n– keinen Preis berechnen\n– keine Machbarkeit freigeben\n– keinen Wert „wahrscheinlich“ auswählen\n– keine fehlende Zahl erfinden\n\nDas Ziel ist frühere Klarheit, nicht ein autonomes Angebot.\n\nWelcher Widerspruch wird in Ihren Projekten am häufigsten erst nach Angebotsabgabe sichtbar?`,
    ],
  },
  'quality-complaint-8d': {
    audience: 'Qualitätsleitung, Reklamationsmanagement, Supplier Quality',
    angles: ['Containment vor Root Cause.', 'Unbelegte Ursachenbehauptung als Hypothese isolieren.', 'Fehlende Charge verhindert saubere Abgrenzung.'],
    hooks: ['„Bestimmt Montagefehler beim Lieferanten“ ist keine Root Cause.', 'Ein 8D-Formular zu füllen ist nicht dasselbe wie eine Ursache zu belegen.', 'Ohne Charge keine saubere Abgrenzung.'],
    ctas: ['Welche Information fehlt bei Reklamationen am häufigsten?', 'Wie trennt Ihr Prozess Hypothese und bestätigte Ursache?', 'Wer darf Containment freigeben?'],
    visual: '8D-Arbeitsgerüst mit D2/D3 gefüllt, D4 bewusst leer; unbelegte Ursache in separater Hypothesenbox.',
    posts: [
      `„Bestimmt Montagefehler beim Lieferanten.“\n\nDas kann eine Hypothese sein. Eine belegte Root Cause ist es nicht.\n\nIm synthetischen 8D-Test steht genau dieser Satz in der Reklamation, aber Ausfallteil und Prüfergebnis fehlen. Der Workflow übernimmt die Behauptung deshalb nicht in D4.\n\nStattdessen bereitet er vor:\n\n– Problembeschreibung und Produkt\n– betroffene Charge und Menge\n– vorhandene Evidenz\n– fehlende Nachweise\n– mögliche Containment-Maßnahmen\n– Verantwortliche und offene Aufgaben\n\nDie Ursachenanalyse bleibt leer und der Fall stoppt zur menschlichen Prüfung.\n\nDer Mehrwert liegt nicht darin, ein 8D-Dokument schneller vollzuschreiben. Er liegt darin, Hypothese, Evidenz und freigegebene Aussage sauber zu trennen.\n\nWie trennt Ihr Reklamationsprozess heute vermutete und bestätigte Ursache?`,
      `Ohne Charge keine saubere Abgrenzung.\n\nEine Reklamation meldet vier Teile mit Kratzern, enthält ein Foto und eine Produktbezeichnung—aber kein Lieferlos.\n\nDamit ist noch unklar:\n\n– welcher Bestand betroffen sein könnte,\n– welche Lieferungen geprüft werden müssen,\n– wie groß das Containment sein sollte,\n– welche Daten für die Analyse fehlen.\n\nDer 8D-Prototyp macht diese Lücke sofort sichtbar und bereitet eine konkrete Rückfrage vor. Er schlägt kein blindes Sperren aller Bestände vor und erfindet keine Chargenzuordnung.\n\nDie menschliche Qualitätsentscheidung bleibt erhalten; die administrative Vorbereitung wird strukturierter.\n\nWelche Information fehlt in eingehenden Reklamationen bei Ihnen am häufigsten?`,
    ],
  },
  'supplier-document-control': {
    audience: 'Supplier Quality, strategischer Einkauf, technische Dokumentation',
    angles: ['Ablaufdaten als Ausnahmeliste statt Ordnersuche.', 'Fehlende Erklärung als Stop Condition.', 'Version und Lieferantenzuordnung prüfbar halten.'],
    hooks: ['Das Zertifikat ist vorhanden. Es läuft in 20 Tagen ab.', 'Ein voller Ordner ist noch kein vollständiger Dokumentensatz.', 'Welche Lieferantendokumente werden erst gesucht, wenn jemand sie dringend braucht?'],
    ctas: ['Welche Dokumentart erzeugt die meisten Rückfragen?', 'Wie früh soll vor Ablauf gewarnt werden?', 'Wo liegt heute die führende Version?'],
    visual: 'Kompakte Dokumentenliste mit Lieferant, Typ, Version, Ablaufampel und fehlender RoHS-Erklärung.',
    posts: [
      `Das Zertifikat ist vorhanden. Es läuft in 20 Tagen ab.\n\nIn vielen Lieferantenordnern ist „vorhanden“ die einzige leicht beantwortbare Frage. Schwieriger sind Version, Gültigkeit, Zuordnung und Vollständigkeit.\n\nDie Synthetic Demo klassifiziert deshalb jeden Eingang nach:\n\n– Lieferant\n– Dokumentart\n– Version\n– gültig bis\n– erwarteter Dokumentensatz\n– fehlende oder bald ablaufende Nachweise\n\nAus dem Ordner wird eine prüfbare Ausnahmeliste. Eine Warnung ist noch keine automatische Lieferantennachricht; sie bereitet die Aufgabe für Supplier Quality oder Einkauf vor.\n\nDer konkrete Nutzen muss noch validiert werden. Technisch ist der Ablauf gebaut und testbar, inklusive fehlender Dokumente und Ablaufwarnung.\n\nWie viele Tage vor Ablauf wäre eine Warnung in Ihrem Prozess wirklich hilfreich?`,
      `Ein voller Ordner ist noch kein vollständiger Dokumentensatz.\n\nIm Test liegen ISO-9001-Zertifikat und Versionsangabe vor. Die erwartete RoHS-Erklärung fehlt.\n\nDer Workflow zählt deshalb nicht einfach Dateien. Er vergleicht den vorhandenen Satz mit einer erwarteten Liste und stoppt den Fall als unvollständig.\n\nWichtig bleibt die Grenze: Ob ein Dokument inhaltlich und rechtlich ausreichend ist, entscheidet die zuständige Fachstelle. Die Automatisierung kann Klassifikation, Fristen und fehlende Typen vorbereiten.\n\nDas ist weniger spektakulär als ein Chatbot—und wahrscheinlich näher an der täglichen Arbeit vieler Einkaufs- und Qualitätsbereiche.\n\nWelche Dokumentart wird bei Ihnen am häufigsten erst dann gesucht, wenn sie dringend gebraucht wird?`,
    ],
  },
  'maintenance-report-actions': {
    audience: 'Instandhaltungsleitung, Service Operations, Produktionsleitung',
    angles: ['PDF-Befunde in verantwortete Maßnahmen überführen.', 'Unklarer Schweregrad als Stop Condition.', 'Frist, Teil und Verantwortliche getrennt prüfen.'],
    hooks: ['Der Wartungsbericht ist abgeschlossen. Die Arbeit daraus noch nicht.', '„Riss an Halterung festgestellt“ reicht nicht für eine automatische Priorität.', 'Wie viele offene Punkte bleiben in Service-PDFs?'],
    ctas: ['Wo werden offene Maßnahmen heute verfolgt?', 'Wer legt bei unklarem Befund den Schweregrad fest?', 'Welche Felder braucht eine CMMS-Aufgabe mindestens?'],
    visual: 'Wartungsbericht links, rechts Aktionsliste mit Befund, Schweregrad, Teil, Owner, Deadline und Quelle.',
    posts: [
      `Der Wartungsbericht ist abgeschlossen. Die Arbeit daraus noch nicht.\n\nIn einem PDF stehen zwei Befunde: erhöhter Verschleiß am Führungswagen und eine verschmutzte Filtermatte. Ohne klare Überführung bleiben daraus schnell informelle Notizen.\n\nDie Demo strukturiert jeden Befund in:\n\n– Beschreibung und Quelle\n– Schweregrad\n– erforderliche Aktion\n– möglicher Ersatzteilbezug\n– verantwortliche Stelle\n– Frist\n\nDanach entsteht ein CMMS-Entwurf—kein echter Systemeintrag. Der Mensch prüft Priorität und Verantwortung.\n\nDas Ziel ist nicht, die technische Bewertung des Wartungspersonals zu ersetzen. Es ist, dass bestätigte offene Punkte nachvollziehbar weiterlaufen.\n\nWo werden Maßnahmen aus Wartungs- und Serviceberichten bei Ihnen heute verfolgt?`,
      `„Riss an Halterung festgestellt.“\n\nMehr Kontext enthält der synthetische Bericht nicht. Keine genaue Lage, kein Foto, kein Schweregrad, keine Sicherheitsbewertung.\n\nEin automatischer Maßnahmenplan wäre hier riskant. Der Workflow stoppt und fordert eine fachliche Einstufung an.\n\nEr darf den Befund strukturieren. Er darf aber nicht entscheiden, ob die Maschine weiterbetrieben werden kann.\n\nGenau diese Grenze ist in der Demo sichtbar: unklarer Schweregrad, fehlende Verantwortung, fehlende Frist und kein externer Write.\n\nWenn Automatisierung administrative Last reduzieren soll, muss sie auch wissen, wann administrative Vollständigkeit nicht für eine technische Entscheidung reicht.\n\nWer legt in Ihrem Prozess bei einem unklaren Befund den Schweregrad fest?`,
    ],
  },
  'trade-fair-lead-processing': {
    audience: 'Vertriebsleitung, Sales Operations, Marketing Operations',
    angles: ['Badge plus Notiz in prüfbaren CRM-Entwurf.', 'Consent-Lücke verhindert Follow-up.', 'Dublette vor CRM-Schreibvorgang sichtbar machen.'],
    hooks: ['Die Messe ist vorbei. Jetzt beginnt das Copy/Paste.', 'Eine Visitenkarte ist keine dokumentierte Follow-up-Erlaubnis.', 'Der Kontakt existiert vielleicht schon—zu 91 Prozent ähnlich.'],
    ctas: ['Welche Information fehlt nach Messen am häufigsten?', 'Wie prüfen Sie Dubletten vor dem CRM-Import?', 'Wo wird die gewünschte Kontaktaufnahme dokumentiert?'],
    visual: 'Badge, Gesprächsnotiz und CRM-Kandidat in drei Spalten; Consent und Dublette als separate Prüfzeilen.',
    posts: [
      `Die Messe ist vorbei. Jetzt beginnt das Copy/Paste.\n\nBadge, Visitenkarte und Gesprächsnotiz liegen getrennt. Firma, Rolle, Interesse und nächster Schritt müssen ins CRM vorbereitet werden.\n\nDer Synthetic Workflow verbindet die Quellen und erzeugt einen prüfbaren Entwurf:\n\n– Firma und Kontakt\n– Rolle\n– konkretes Interesse\n– fehlende Angaben\n– möglicher bestehender CRM-Kontakt\n– dokumentierter Follow-up-Wunsch\n– vorbereiteter Text für den nächsten Schritt\n\nGeschrieben wird noch nichts. Gerade bei Dubletten oder unklarem Consent muss Sales Operations prüfen.\n\nDer Prozess ist leicht zu demonstrieren, aber saisonaler und weniger industriespezifisch als Service oder Auftragseingang. Deshalb bleibt er im Lab ein funktionaler Prototyp, nicht einer der drei Favoriten.\n\nWelche Information fehlt nach einer Messe bei Ihnen am häufigsten?`,
      `Eine Visitenkarte ist keine dokumentierte Follow-up-Erlaubnis.\n\nIm Testfall enthält der Badge Name und Firma, die Notiz aber nur „kurzes Gespräch am Stand“. Rolle, Interesse und gewünschte Kontaktaufnahme sind unklar.\n\nDer Workflow erstellt deshalb keinen freigegebenen Follow-up-Entwurf. Er markiert die Lücken und stoppt vor dem CRM-Write.\n\nDas ist bewusst konservativ. Ein System sollte fehlenden Kontext nicht mit einem freundlichen Standardtext überdecken.\n\nAuch die Kontaktdaten im Lab sind synthetisch und verwenden nicht zustellbare Beispieladressen. Es wird keine Nachricht gesendet.\n\nWo und wie wird bei Ihnen festgehalten, dass ein Messekontakt tatsächlich eine Kontaktaufnahme erwartet?`,
    ],
  },
};
