-- Hugo Menz Industrial Automation Lab
-- Synthetic test-account schema only. No customer or production data.

create extension if not exists pgcrypto;

create table if not exists public.industrial_lab_cases (
  id uuid primary key default gen_random_uuid(),
  correlation_id text not null,
  workflow_code text not null,
  title text not null,
  source_type text not null,
  source_asset_url text,
  status text not null,
  priority text not null default 'normal',
  current_department text,
  extracted_data jsonb not null default '{}'::jsonb,
  exception_data jsonb not null default '{}'::jsonb,
  human_decision jsonb not null default '{"required":true,"state":"pending"}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists industrial_lab_cases_correlation_uq
  on public.industrial_lab_cases (correlation_id);
create index if not exists industrial_lab_cases_status_idx
  on public.industrial_lab_cases (status, current_department);

create table if not exists public.industrial_lab_documents (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.industrial_lab_cases(id) on delete cascade,
  kind text not null,
  file_name text not null,
  mime_type text not null,
  storage_path text,
  sha256 text,
  page_count integer,
  classification text,
  extracted_fields jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.industrial_lab_events (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.industrial_lab_cases(id) on delete cascade,
  event_type text not null,
  department text,
  actor_type text not null,
  actor_label text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists industrial_lab_events_case_idx
  on public.industrial_lab_events (case_id, created_at);

create table if not exists public.industrial_lab_approvals (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.industrial_lab_cases(id) on delete cascade,
  department text not null,
  decision text not null default 'pending',
  decided_by text,
  rationale text,
  version integer not null default 1,
  created_at timestamptz not null default now()
);
create index if not exists industrial_lab_approvals_case_idx
  on public.industrial_lab_approvals (case_id, decision);

create table if not exists public.industrial_lab_agent_runs (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.industrial_lab_cases(id) on delete cascade,
  correlation_id text not null,
  agent_name text not null,
  model_provider text not null,
  model_id text not null,
  task text not null,
  status text not null,
  confidence numeric,
  input_refs jsonb not null default '{}'::jsonb,
  output jsonb not null default '{}'::jsonb,
  error jsonb,
  latency_ms integer,
  created_at timestamptz not null default now()
);
create index if not exists industrial_lab_agent_runs_case_idx
  on public.industrial_lab_agent_runs (case_id, created_at);

create table if not exists public.industrial_lab_master_data (
  id uuid primary key default gen_random_uuid(),
  domain text not null,
  external_key text not null,
  data jsonb not null,
  updated_at timestamptz not null default now()
);
create unique index if not exists industrial_lab_master_data_domain_key_uq
  on public.industrial_lab_master_data (domain, external_key);

alter table public.industrial_lab_cases enable row level security;
alter table public.industrial_lab_documents enable row level security;
alter table public.industrial_lab_events enable row level security;
alter table public.industrial_lab_approvals enable row level security;
alter table public.industrial_lab_agent_runs enable row level security;
alter table public.industrial_lab_master_data enable row level security;

-- No anon/authenticated policies are created. n8n uses a server-only test credential.
insert into public.industrial_lab_master_data (domain, external_key, data)
values
  ('customer', 'K-1042', '{"name":"Musterwerk Sued GmbH","terms":"30 Tage netto","ship_to":"Werkstrasse 18, Stuttgart","synthetic":true}'::jsonb),
  ('article', 'HM-AX-240', '{"description":"Achseinheit 240","price":1280,"currency":"EUR","status":"released","synthetic":true}'::jsonb),
  ('article', 'HM-SEN-18', '{"description":"Naeherungssensor M18","price":84.5,"currency":"EUR","status":"released","synthetic":true}'::jsonb),
  ('machine', 'MX-24-0187', '{"family":"Montagezelle MX-24","site":"Werk Stuttgart","last_service":"2025-11-14","synthetic":true}'::jsonb),
  ('error_code', 'E-217', '{"label":"Axis reference not completed","boundary":"context_only_no_diagnosis","synthetic":true}'::jsonb),
  ('supplier', 'L-2091', '{"name":"Muster Pneumatik GmbH","approved_iban":"DE02100100100000000004","synthetic":true}'::jsonb),
  ('purchase_order', 'PO-78133', '{"supplier_id":"L-2091","items":[{"sku":"VLV-24","quantity":10,"unit_price":94}],"currency":"EUR","synthetic":true}'::jsonb),
  ('goods_receipt', 'PO-78133', '{"items":[{"sku":"VLV-24","quantity":10}],"synthetic":true}'::jsonb)
on conflict (domain, external_key) do update
set data = excluded.data, updated_at = now();
